### ISSUE TITLE
Override Name attribute in Override Value

### ISSUE THREAD

**Issue by x64Eddie** [sketch-hq/sketch-file-format#123]
Greetings, 
I am currently working with some sketch files and I am having some trouble understanding the `override-name` attribute. I have a symbol instance that contains a couple of overridable values, however, it contains a value that I have not seen in the `override-name.schema.yaml`.
The following image contains the value that I am getting for the `overrideName` for a specific `OverrideValue`.

![image](https://user-images.githubusercontent.com/29381845/97237361-8c43cf00-17ac-11eb-9a0e-b55db2c77abb.png)

However, in the `override-name.schema.yaml` there is no specification for `_layerStyle`. Furthermore, would that specification describe multiple UUIDs (as seen in the screenshot)? 🤔 
Thanks in advance for the help! 😄 

#### Override Name
```
title: Override Name
description: Defines the valid string patterns for an override name
oneOf:
  - type: string
    pattern: '^[0-9A-F]{8}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{12}_stringValue$'
  - type: string
    pattern: '^[0-9A-F]{8}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{12}_symbolID$'
  - type: string
    pattern: '^[0-9A-F]{8}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{12}_image$'
```

#### Override Value
```
title: Override Value
description: Defines an individual symbol override
type: object
optional:
  - do_objectID
properties:
  _class: { const: overrideValue }
  do_objectID: { $ref: ../utils/uuid.schema.yaml }
  overrideName: { $ref: ./override-name.schema.yaml }
  value:
    oneOf:
      - { type: string }
      - { $ref: ../utils/uuid.schema.yaml }
      - { $ref: ./file-ref.schema.yaml }
      - { $ref: ./data-ref.schema.yaml }
```
