### ISSUE TITLE
Incorrect usage of ExclusiveMinimum

### ISSUE THREAD

**Issue by raveclassic** [sketch-hq/sketch-file-format#29]
Hi, 

Looks like `gradient` schema is incorrect according to [JSON Schema 7](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.5) in the following lines: https://github.com/sketch-hq/sketch-file-format/blob/d61c8a2e3d81ecfe0890d39e1a48f2add77801cb/schema/objects/gradient.schema.yaml#L10-L13

`exclusiveMinimum` should be defined on numeric instances according to spec. Is it a bug or 
 some extension like #28?

**Comment by raveclassic** [comment]
Looks like there's another place where `exlusiveMimimum` is not aligned with JSON Schema 7: 
https://github.com/sketch-hq/sketch-file-format/blob/d61c8a2e3d81ecfe0890d39e1a48f2add77801cb/schema/objects/border.schema.yaml#L10-L12
Should be:
```yaml
thickness:
    type: number
    minimum: 0
    exclusiveMinimum: true
```
or 
```yaml
thickness:
    type: number
    exclusiveMinimum: false
```
